### ISSUE TITLE
Improve content sections linking

### ISSUE THREAD

**Issue by maria** [rosedu/sites_template#3]
### Problem

When clicking on a menu link for a page section, you're not directed to the correct part of the section.

For example when you click for `projects` you will be directed
to this part of the page:

![screenshot 2015-02-01 19 00 13](https://cloud.githubusercontent.com/assets/1681405/5992888/e3c86bae-aa44-11e4-8a32-4b5ce9ad993f.png)

when you should be directed to this part:

![screenshot 2015-02-01 19 02 48](https://cloud.githubusercontent.com/assets/1681405/5992890/f65173b0-aa44-11e4-92bd-4edc45ac1304.png)

**Comment by dinuand** [comment]
I think we are done with this now. :dart:
